name: quality

on:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.3

      - name: build
        run: |
          make build
